### ISSUE TITLE
Allow running unprivileged containers

### ISSUE THREAD

**Issue by psamaan** [opctl/opctl#459]
## Problem
Running privileged containers on CI/CD servers is dangerous, and an actual blocker in multi-tenant environments.

## Proposal
Add `isPrivileged` as a Boolean property on `container` declarations, with default of `false`.

**Comment by chrisdostert** [comment]
Theres a lot of things to think about surrounding this request.

Privileges are currently obviously left as a hosting concern. No hosted service is going to allow you to request privileged execution and all of a sudden you can access other tenants containers... that would be an obvious security fail. 

There are many ways to achieve the above such as configuring your container runtime to dis-allow privileged execution across the board, to choosing a runtime that has enforces strict security isolation such as katacontainers, etc...

Simply adding an attribute on a container declaration in and of itself wouldn't seem to solve anything. To be of any use it would seem like you'd need to introduce some higher level concept of privilege at the level of running an op (or higher.. maybe for an entire node or net), to either allow/dis-allow any container declaration in a call graph requesting privileged execution (or other things like resources etc...)

All the above said, any higher level privilege mechanisms would need the ops to declare what they needed in order to run so maybe adding an attribute could at least be a first step.

**Comment by chrisdostert** [comment]
That was a long winded way of saying this sounds fair enough but having this doesn't solve the problem alone; it's just a pre-requisite to solving the problem.

**Comment by psamaan** [comment]
Completely agree
