### ISSUE TITLE
opctl ls on windows does not list anything

### ISSUE THREAD

**Issue by yanilkr** [opctl/opctl#460]
I cloned a project on windows that works well on mac and linux. 
I run opctl ls on windows and it lists nothing

![image](https://user-images.githubusercontent.com/195142/52509663-dc7c9700-2bad-11e9-8f28-97fb835f8bcb.png)

![image](https://user-images.githubusercontent.com/195142/52509670-e1d9e180-2bad-11e9-9bcb-ba426dc61ddc.png)

![image](https://user-images.githubusercontent.com/195142/52509687-f1f1c100-2bad-11e9-8369-571c92038d29.png)

I noticed that all ops that need to create files/folders on windows host.

I can actually invoke an op e.g
opctl run pgsql 

It pulls all dependent docker images but fails with out starting.

Platform: Windows
Docker version: 18.09.1 Community edition

**Comment by chrisdostert** [comment]
repro'd on azure Windows 10 pro D4_v3 VM

**Comment by chrisdostert** [comment]
@yanilkr I cannot repro the issue you're experiencing with running ops. I'm guessing your docker filesystem sharing might have invalid credentials. You might try un sharing your drive, running ops, and docker should prompt you to re-enter your credentials

**Comment by chrisdostert** [comment]
@yanilkr were you able to see if it was the credentials?

**Comment by yanilkr** [comment]
@chrisdostert, I can repro this issue again on a different windows computer. I also tried to set and unset sharing disks in docker settings, tried running shell using administrator, created a new project with one op. In all cases I cannot list the ops for the project.  

I am using latest windows 10, docker and opctl.

**Comment by chrisdostert** [comment]
@yanilkr, I'm not sure if we're understanding each other completely. It's a little bit confusing because this issue as filed  is actually two issues. 
1) `opctl ls` on windows (I can repro this)
2) `opctl run` on windows (I cannot repro this)

I was trying to see if you could double check 2).  Best -CD

**Comment by yanilkr** [comment]
@chrisdostert , 

I tried opctl run on some simple tasks like creating a folder. It works fine.

I tried opctl run to start a postgres database. It had so many errors. Most of them are file system related permissions. It could be something like folder created by one docker image may not be reusable by other docker container on windows.

I tried to unshare the drive and re run it again.  This is the same error

[91;1mOpErred Id='14ef09da3ab846a286b07023df8fde51' OpRef='C:\Users\user\sdev\orderbookapi\.opspec\pgsql' Timestamp='2019-02-18T18:42:41Z' Msg='Error response from daemon: Mount denied:
The source path "C:/Users/user/sdev/orderbookapi/db/data/postgres"
doesn't exist and is not known to Docker'

**Comment by yanilkr** [comment]
I also tried to reset credentials couple of times. Its still same error.

**Comment by chrisdostert** [comment]
@yanilkr per slack discussion, thanks for the patience and sharing your ops. I can also repro your issue w/ `opctl run` on windows using them.

**Comment by chrisdostert** [comment]
@yanilkr a fix for `opctl ls` is available in alpha channel; u can upgrade via `opctl self-update -c alpha`
unfortunately the issue you're experiencing with the postgresql op seems to be caused by postgres. It seems to require the data dir owner is also the owner of the process starting the postgres bin. Theres some differences between windows and linux here because on windows the files will be shared with the container via SMB
