### ISSUE TITLE
Server restart

### ISSUE THREAD

**Issue by RoynKo** [opctl/opctl#515]
The opctl server died because of unspecified reason, and returned error as below:
```
request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/starts: dial tcp [::1]:42224: connect: connection refused
```

I tried to restart Docker but nothing changed, the only solution works so far is restart the laptop. Is there any easier way to restart the opctl server?

**Comment by chrisdostert** [comment]
when you run a command from the CLI that requires a node running (such as `opctl events` or `opctl run`), the CLI will attempt to communicate w/ the node running at the conventional network address `localhost:42224`. If it can't find one it will try to start one as a daemonized process (background process with no parent) which allows it to remain running after the current process exits. Unfortunately this also makes it so you see no error messages from that process. 

The error you're seeing is because the CLI can't communicate w/ or start a node & it keep trying up to 3 times. 

To get to the bottom of it, run `opctl node create` which will create a node in process and block (rather than as a background process, which will allow you to see any errors happening as part of the node startup. 

A common reason is due to permissions.

**Comment by chrisdostert** [comment]
@RoynKo if this solved your issue, could you close it out? Thanks!

**Comment by RoynKo** [comment]
@chrisdostert, opctl node crashed on my computer couple of times. I did not know how to capture important logs. I will close this issue for now but if it happens again, I will provide more log details.
