### ISSUE TITLE
opctl only able to work with sudo

### ISSUE THREAD

**Issue by kjlim1982** [opctl/opctl#622]
I just install the opctl, but I only able to run the op with 'sudo' eg. sudo opctl run xxx. without the sudo I get this error:

request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/starts: dial tcp 127.0.0.1:42224: getsockopt: connection refused
request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/starts: dial tcp 127.0.0.1:42224: getsockopt: connection refused
request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/starts: dial tcp 127.0.0.1:42224: getsockopt: connection refused
Post http://localhost:42224/api/ops/starts: dial tcp 127.0.0.1:42224: getsockopt: connection refused

**Comment by zachpuck** [comment]
Hi @kjlim1982 
A possible reason you are running into this issue is opctl starts a node at the path listed there under your account. This node may have started undo sudo instead and is now unable to access it. 

You can try a few things to see the cause. 
run `sudo lsof -i -P -n | grep LISTEN` to see if opctl is listening and under what user. If it is running under root then go ahead and kill this node by running `sudo opctl node kill`.

Then without sudo try running `opctl node create`. You may find that you get an error message similar to `unable to cleanup DCG (dynamic call graph) data at path: /home/foo/opctl/dcg` this indicates that some of the data associated with opctl is owned by root. To resolve this error run `sudo rm -rf /home/foo/opctl/dcg`. This will clean up any of the opctl nodes data. 

If you are at this state you should now be able to run a simple op like `opctl run github.com/opspec-pkgs/uuid.v4.generate#1.1.0` and it will automatically start a new opctl node under your account. 

Hope this helps. If you get a different error when running `opctl node create` please let us know.

**Comment by chrisdostert** [comment]
Alternatively it could be if your active user does not have permission to access the docker daemon. You can solve that by adding your current user to the docker group.

**Comment by kjlim1982** [comment]
Thanks, problem solved
