### ISSUE TITLE
stdout from the underlying command of the op has no way to be redirected properly

### ISSUE THREAD

**Issue by zimnyjakub** [opctl/opctl#714]
## 🐛 Bug Report

stout is being polluted by opctl logging, rendering the output not being able to being piped properly

## To Reproduce

Run an op

## Expected behavior

Non application logs should be using stderr or there should be verbosity leveling done via arguments or configuration

## Actual Behavior

 Opctl just spits everything out (including coloring characters) across the pipe

**Comment by chrisdostert** [comment]
@zimnyjakub thanks for filing. I'm not sure this is a bug as much as a proposal.  

> tip re: coloring, you can disable color via https://opctl.io/docs/cli/reference/commands#--no-color-since-v0115

If we're using POSIX conventions https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap01.html#tag_17_04

it states "Default Behavior: When this section is listed as "The standard error shall be used only for diagnostic messages.", it means that, unless otherwise stated, the diagnostic messages shall be sent to the standard error only when the exit status indicates that an error occurred and the utility is used as described by this volume of POSIX.1-2017."

Since we're not returning non-zero exit code I'm not sold we should be writing to stderr. Seems like what you're really after is just more output formatting capabilities. There are a few outstanding tickets in this regard:

- https://github.com/opctl/opctl/issues/76
- https://github.com/opctl/opctl/issues/62
- https://github.com/opctl/opctl/issues/664

**Comment by chrisdostert** [comment]
closing this one for now as a dupe; I think we can track via the tickets linked above
